# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoffeeForm(object):
    def setupUi(self, CoffeeForm):
        CoffeeForm.setObjectName("CoffeeForm")
        CoffeeForm.resize(521, 472)
        self.buttonBox = QtWidgets.QDialogButtonBox(CoffeeForm)
        self.buttonBox.setGeometry(QtCore.QRect(420, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(CoffeeForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 381, 381))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.blend_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.blend_name.setObjectName("blend_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.blend_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.roasting = QtWidgets.QComboBox(self.formLayoutWidget)
        self.roasting.setObjectName("roasting")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roasting)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.is_ground = QtWidgets.QComboBox(self.formLayoutWidget)
        self.is_ground.setObjectName("is_ground")
        self.is_ground.addItem("")
        self.is_ground.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.is_ground)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.price = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.price.setMaximum(999999.99)
        self.price.setObjectName("price")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.price)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.volume = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.volume.setMaximum(10000)
        self.volume.setObjectName("volume")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.volume)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.taste_description = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.taste_description.setObjectName("taste_description")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.taste_description)

        self.retranslateUi(CoffeeForm)
        self.buttonBox.accepted.connect(CoffeeForm.accept)
        self.buttonBox.rejected.connect(CoffeeForm.reject)
        QtCore.QMetaObject.connectSlotsByName(CoffeeForm)

    def retranslateUi(self, CoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        CoffeeForm.setWindowTitle(_translate("CoffeeForm", "Добавление / редактирование записи"))
        self.label.setText(_translate("CoffeeForm", "название сорта"))
        self.label_2.setText(_translate("CoffeeForm", "степень обжарки"))
        self.label_3.setText(_translate("CoffeeForm", "молотый/в зернах"))
        self.is_ground.setItemText(0, _translate("CoffeeForm", "молотый"))
        self.is_ground.setItemText(1, _translate("CoffeeForm", "в зернах"))
        self.label_4.setText(_translate("CoffeeForm", "цена (руб)"))
        self.label_5.setText(_translate("CoffeeForm", "объем упаковки (гр)"))
        self.label_6.setText(_translate("CoffeeForm", "описание вкуса"))
